# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: all-ci-checks
        name: All CI Checks
        description: This hook executes a all checks listed in the `check.py`.
        entry: 'python tools/check.py -s'
        language: python
        types: [ python ]
        stages: [ pre-commit, manual ]
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: no-commit-to-branch
        args: [ '--branch', 'main' ]
